### PR TITLE
Update to SDK 8.2.6

### PR DESCRIPTION
**Pull request by codescape**

### CODE REVIEW

**Comment by codescape** [comment]
Do you need further information to accept this PR?

**Comment by Mihailoff** [comment]
+1

**Comment by codescape** [comment]
Last activity of the team in this repository is 17 months ago... I have big doubts anything will happen here... :(

**Comment by andrewswan** [comment]
> I have big doubts anything will happen here
It's been brought to the right people's attention now, please give us a little more time. Thanks for your patience.

**Comment by ChrisPWillAtl** [comment]
Hi @codescape , thanks for the contribution! I've made a couple of updates as a newer version of the SDK has just been released. Apologies for the delay, 8.2.2 was actually not an official SDK release due to a bug in the installer preventing some users from installing successfully). I've updated the version accordingly.

**Pull request merged**
